# Verify image that was signed with a GitHub SBOM attestation
apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-github-sbom-attestations
spec:
  validationActions: [Deny]
  failurePolicy: Fail
  webhookConfiguration:
    timeoutSeconds: 15
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
  matchImageReferences:
    - glob: "ghcr.io/dolisss/demo-github-attestations-sbom:*"
  attestations:
    - name: sbom
      intoto:
        type: https://spdx.dev/Document/v2.3
  attestors:
    - name: cosign
      cosign:
        keyless:
          identities:
            - subject: "https://github.com/dolisss/demo-github-attestations-sbom/.github/workflows/ci.yml@refs/heads/main"
              issuer: "https://token.actions.githubusercontent.com"
        ctlog:
          url: "https://rekor.sigstore.dev"
  validations:
    - expression: >-
        images.containers.map(image,
          verifyAttestationSignatures(image, attestations.sbom, [attestors.cosign])
        ).all(e, e > 0)
      message: "Failed to verify SPDX SBOM attestation"
